// Generated by CoffeeScript 1.7.1
(function() {
  var indexToDay, _ref;

  this.BH = typeof BH !== "undefined" && BH !== null ? BH : {};

  BH.Workers = (_ref = BH.Workers) != null ? _ref : {};

  BH.Workers.DayGrouper = (function() {
    function DayGrouper() {
      this.days = [
        {
          name: 'Sunday',
          visits: []
        }, {
          name: 'Monday',
          visits: []
        }, {
          name: 'Tuesday',
          visits: []
        }, {
          name: 'Wednesday',
          visits: []
        }, {
          name: 'Thursday',
          visits: []
        }, {
          name: 'Friday',
          visits: []
        }, {
          name: 'Saturday',
          visits: []
        }
      ];
    }

    DayGrouper.prototype.run = function(visits) {
      var day, dayName, index, visit, _i, _j, _len, _len1, _ref1;
      for (_i = 0, _len = visits.length; _i < _len; _i++) {
        visit = visits[_i];
        dayName = indexToDay(new Date(visit.lastVisitTime).getDay());
        _ref1 = this.days;
        for (index = _j = 0, _len1 = _ref1.length; _j < _len1; index = ++_j) {
          day = _ref1[index];
          if (day.name === dayName) {
            this.days[index].visits.push(visit);
            break;
          }
        }
      }
      return this.days;
    };

    return DayGrouper;

  })();

  indexToDay = function(index) {
    var days;
    days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    return days[index];
  };

  if (typeof onServer === "undefined" || onServer === null) {
    self.addEventListener('message', function(e) {
      var dayGrouper;
      dayGrouper = new BH.Workers.DayGrouper();
      return postMessage(dayGrouper.run(e.data.visits));
    });
  }

}).call(this);
