// Generated by CoffeeScript 1.7.1
(function() {
  var RangeSanitizer, getDomain;

  RangeSanitizer = (function() {
    function RangeSanitizer() {}

    RangeSanitizer.prototype.run = function(results, options) {
      var prunedResults, result, _i, _len;
      this.options = options;
      prunedResults = [];
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        result = results[_i];
        if (this.verifyDateRange(result)) {
          result.location = result.url;
          result.host = getDomain(result.url);
          result.title || (result.title = '(No title)');
          this.removeScriptTags(result);
          prunedResults.push(result);
        }
      }
      prunedResults.sort(this.sortByTime);
      return prunedResults;
    };

    RangeSanitizer.prototype.verifyDateRange = function(result) {
      return result.lastVisitTime > this.options.startTime && result.lastVisitTime < this.options.endTime;
    };

    RangeSanitizer.prototype.removeScriptTags = function(result) {
      var property, regex, _i, _len, _ref, _results;
      regex = /<(.|\n)*?>/ig;
      _ref = ['title', 'url', 'location'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        property = _ref[_i];
        _results.push(result[property] = result[property].replace(regex, ""));
      }
      return _results;
    };

    RangeSanitizer.prototype.setAdditionalProperties = function(result) {
      return result.location = result.url;
    };

    RangeSanitizer.prototype.sortByTime = function(a, b) {
      if (a.lastVisitTime > b.lastVisitTime) {
        return -1;
      }
      if (a.lastVisitTime < b.lastVisitTime) {
        return 1;
      }
      return 0;
    };

    return RangeSanitizer;

  })();

  getDomain = function(url) {
    var match;
    match = url.match(/\w+:\/\/(.*?)\//);
    if (match === null) {
      return null;
    } else {
      return match[0];
    }
  };

  if (typeof self !== "undefined" && self !== null) {
    self.addEventListener('message', function(e) {
      var sanitizer;
      sanitizer = new RangeSanitizer();
      return postMessage(sanitizer.run(e.data.results, e.data.options));
    });
  }

}).call(this);
