// Generated by CoffeeScript 1.7.1
(function() {
  var RangeSanitizer, timeOfEvent;

  RangeSanitizer = (function() {
    function RangeSanitizer() {}

    RangeSanitizer.prototype.run = function(results, options) {
      var out, result, _i, _len;
      this.options = options;
      out = [];
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        result = results[_i];
        if (this.verifyDateRange(result)) {
          out.push(result);
        }
      }
      out.sort(this.sortByTime);
      return out;
    };

    RangeSanitizer.prototype.verifyDateRange = function(result) {
      var time;
      time = timeOfEvent(result);
      return time > this.options.startTime && time < this.options.endTime;
    };

    RangeSanitizer.prototype.sortByTime = function(a, b) {
      var aTime, bTime;
      aTime = timeOfEvent(a);
      bTime = timeOfEvent(b);
      if (aTime > bTime) {
        return -1;
      }
      if (aTime < bTime) {
        return 1;
      }
      return 0;
    };

    return RangeSanitizer;

  })();

  timeOfEvent = function(result) {
    return result.lastVisitTime || new Date(result.startTime).getTime();
  };

  if (typeof onServer !== "undefined" && onServer !== null) {
    module.exports = RangeSanitizer;
  } else {
    self.addEventListener('message', function(e) {
      var sanitizer;
      sanitizer = new RangeSanitizer();
      return postMessage(sanitizer.run(e.data.results, e.data.options));
    });
  }

}).call(this);
