// Generated by CoffeeScript 1.7.1
(function() {
  var ChromeHistoryAPI, Day;

  ChromeHistoryAPI = require('./chrome_history_api');

  Day = (function() {
    function Day(date) {
      date.setHours(0, 0, 0, 0);
      this.startTime = date.getTime();
      date.setHours(23, 59, 59, 999);
      this.endTime = date.getTime();
      this.history = new ChromeHistoryAPI;
    }

    Day.prototype.fetch = function(callback) {
      var options;
      if (callback == null) {
        callback = function() {};
      }
      options = {
        startTime: this.startTime,
        endTime: this.endTime,
        text: '',
        maxResults: 5000
      };
      return this.history.query(options, (function(_this) {
        return function(results) {
          var worker;
          options = {
            options: options,
            results: results
          };
          worker = new Worker('workers/range_sanitizer.js');
          worker.postMessage(options);
          return worker.onmessage = function(e) {
            if (e.data.log) {
              return console.log(e.data.log);
            } else {
              callback(e.data);
              return worker.terminate();
            }
          };
        };
      })(this));
    };

    Day.prototype.destroy = function(callback) {
      var options;
      if (callback == null) {
        callback = function() {};
      }
      options = {
        startTime: this.startTime,
        endTime: this.endTime
      };
      return this.history.deleteRange(options, (function(_this) {
        return function() {
          return callback();
        };
      })(this));
    };

    Day.prototype.destroyHour = function(hour, callback) {
      var endTime, options, startTime;
      if (callback == null) {
        callback = function() {};
      }
      startTime = new Date(this.startTime);
      startTime.setHours(hour);
      endTime = new Date(this.endTime);
      endTime.setHours(hour);
      options = {
        startTime: startTime.getTime(),
        endTime: endTime.getTime()
      };
      return this.history.deleteRange(options, (function(_this) {
        return function() {
          return callback();
        };
      })(this));
    };

    return Day;

  })();

  module.exports = Day;

}).call(this);
